name: Feature Request
description: Create a feature request to help us keep track of all features you want to be added
title: "[FEATURE] <title>"
labels: [ feature ]

body:
  - type: "checkboxes"
    id: "i-have-checked"
    attributes:
      label: "I have checked that..."
      options:
        - label: "...such a feature does not exist already"
          required: true
        - label: "...such a feature request has not been submitted already"
          required: true
  - type: "textarea"
    id: "description"
    attributes:
      label: "Description"
      description: "A full description of the feature"
    validations:
      required: true
  - type: "textarea"
    id: "config-changes"
    attributes:
      label: "Config Changes"
      description: "The configuration changes your feature should have"
    validations:
      required: true
  - type: "dropdown"
    id: "type"
    attributes:
      label: "How significant is the feature?"
      options:
        - "Huge - Requires many changes in the current structure"
        - "Moderate - Needs moderate changes to the current structure"
        - "Meerly Significant - Small feature fitting perfectly into the current structure"
    validations:
      required: true
