name: Build and deploy documentation to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'dependabot') && !contains(github.event.head_commit.message, 'nodocs')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 16
      - uses: gradle/gradle-build-action@v2
      - name: Build HTML
        run: ./gradlew dokkaHtml --no-daemon --stacktrace
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build/dokka/html'

  deploy:
    if: "!contains(github.event.head_commit.message, 'dependabot')"
    environment:
      name: github-pages
      url: 'https://skyslycer.github.io/SkyLib/'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1